<?php

namespace App\Models;

use App\Services\Ai\Classification;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;

class Report extends Model
{
    use HasFactory;

    public const STATUS_PENDING = 'pending';
    public const STATUS_IN_PROGRESS = 'in_progress';
    public const STATUS_RESOLVED = 'resolved';
    public const STATUS_REJECTED = 'rejected';

    protected $guarded = ['id'];

    protected function casts(): array
    {
        return [
            'extra_photos' => 'array',
            'detected_items' => 'array',
            'latitude' => 'float',
            'longitude' => 'float',
            'ai_confidence' => 'integer',
            'estimated_weight_kg' => 'integer',
            // Nullable casts: null means "never assessed", which is a different
            // answer from 0 litres or from "not compostable".
            'is_compostable' => 'boolean',
            'estimated_volume_litres' => 'integer',
            'rating' => 'integer',
            'analysed_at' => 'datetime',
            'scheduled_for' => 'datetime',
            'resolved_at' => 'datetime',
            'rejected_at' => 'datetime',
            'accepted_at' => 'datetime',
            'settled_at' => 'datetime',
            'citizen_confirmed_at' => 'datetime',
            'offer_amount' => 'float',
            'settled_amount' => 'float',
            'settled_weight_kg' => 'float',
        ];
    }

    protected static function booted(): void
    {
        static::creating(function (Report $report) {
            $report->reference ??= static::nextReference();

            // Ward comes from where the waste is, not from who reported it.
            // Left null when the point falls outside every mapped ward — that
            // is a real answer ("outside corporation limits"), not a failure to
            // paper over with a default.
            if (! $report->ward_id && $report->latitude && $report->longitude) {
                $report->ward_id = Ward::containing((float) $report->latitude, (float) $report->longitude)?->id;
            }
        });
    }

    public function ward(): BelongsTo
    {
        return $this->belongsTo(Ward::class);
    }

    /** Reference numbers start here, so the first one doesn't read as "WN-00001". */
    private const REFERENCE_BASE = 24800;

    /**
     * Sequential, human-quotable id. Citizens read these out over the phone,
     * so it stays short and avoids ambiguous characters by being numeric.
     *
     * Derived from the highest reference already issued, NOT from max(id).
     * The two are only in step if every reference was ever generated by this
     * method — and the seeder assigns its own, out of order, so id 1 holds
     * WN-24810 while max(id) is 9. That made this method return WN-24810 for
     * every new report and made submission fail outright on the unique index.
     *
     * Reference numbers are also a promise to the citizen: they must never be
     * reused, so anchoring them to the highest one issued is correct even after
     * rows are deleted, whereas max(id) can regress.
     */
    public static function nextReference(): string
    {
        // Numeric part only; a stray non-conforming reference can't drag the
        // sequence backwards or blow up the cast.
        $highest = (int) static::query()
            ->where('reference', 'like', 'WN-%')
            ->selectRaw('MAX(CAST(SUBSTRING(reference, 4) AS UNSIGNED)) as n')
            ->value('n');

        return 'WN-'.str_pad((string) (max($highest, self::REFERENCE_BASE) + 1), 5, '0', STR_PAD_LEFT);
    }

    /**
     * Create a report, retrying if another request took the same reference.
     *
     * nextReference() reads the current maximum and adds one, so two
     * submissions landing together will generate the same string. The unique
     * index is what actually guarantees uniqueness; this makes the loser retry
     * instead of failing the citizen's submission. Each attempt builds a fresh
     * model, so the creating hook issues a new reference rather than reusing
     * the one that just lost.
     *
     * Only a reference collision is retried — any other database error is a
     * real fault and is rethrown immediately.
     */
    public static function createWithReference(array $attributes, int $attempts = 4): self
    {
        for ($attempt = 1; ; $attempt++) {
            try {
                return static::create($attributes);
            } catch (QueryException $e) {
                if ($attempt >= $attempts || ! self::isReferenceCollision($e)) {
                    throw $e;
                }

                // Jitter, so two clients that collided don't collide again in
                // lockstep on the next attempt.
                usleep(random_int(1_000, 8_000));
            }
        }
    }

    private static function isReferenceCollision(QueryException $e): bool
    {
        return ($e->errorInfo[1] ?? null) === 1062
            && str_contains($e->getMessage(), 'reports_reference_unique');
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function assignee(): BelongsTo
    {
        return $this->belongsTo(User::class, 'assigned_to');
    }

    public function events(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(ReportEvent::class);
    }

    public function resolver(): BelongsTo
    {
        return $this->belongsTo(User::class, 'resolved_by');
    }

    public function scopeResolved($query)
    {
        return $query->where('status', self::STATUS_RESOLVED);
    }

    public function scopeOpen($query)
    {
        return $query->whereIn('status', [self::STATUS_PENDING, self::STATUS_IN_PROGRESS]);
    }

    /** Municipal work: what the ward crews clear. */
    public function scopeDisposal($query)
    {
        return $query->where('stream', Classification::STREAM_DISPOSAL);
    }

    /** Scrap work: what contractors buy. */
    public function scopeRecyclable($query)
    {
        return $query->where('stream', Classification::STREAM_RECYCLABLE);
    }

    /**
     * The contractor pool: recyclable, still open, and nobody has claimed it.
     *
     * Deliberately excludes anything already accepted — two contractors
     * driving to the same address is the failure this feature would be
     * remembered for.
     */
    public function scopeAvailableToContractors($query)
    {
        return $query->recyclable()
            ->where('status', self::STATUS_PENDING)
            ->whereNull('assigned_to');
    }

    public function isRecyclable(): bool
    {
        return $this->stream === Classification::STREAM_RECYCLABLE;
    }

    public function contractor(): BelongsTo
    {
        return $this->belongsTo(User::class, 'assigned_to');
    }

    /**
     * Label the UI shows on status pills.
     */
    public function statusLabel(): string
    {
        return Str::headline($this->status);
    }
}
